on: [push, pull_request]
name: build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Format Unix
      if: runner.os == 'Linux'
      run: test -z $(go fmt ./...)
    - name: Test
      run: go test -v ./...
  staticcheck:
    name: "Run staticcheck"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - uses: dominikh/staticcheck-action@ba605356b4b29a60e87ab9404b712f3461e566dc
      with:
        version: "2022.1"
